# Generated by Django 5.2.5 on 2025-08-27 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihicl_main', '0005_nextofkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ihicl_main.investmentopportunity'),
        ),
    ]
