# Generated by Django 5.2.5 on 2025-08-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihicl_main', '0007_investorprofile_other_title_investorprofile_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='newsletter_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
