# Generated by Django 5.2.5 on 2025-08-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihicl_main', '0010_statementrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementrequest',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
